dolphins/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	path('contact/', views.contact, name='contact'),
	path('services/', views.services, name='services'),
	path('portfolio/', views.portfolio, name='portfolio'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

def home(request):
	return render(request, 'index.html')

def about(request):
	return render(request, 'about.html')

def services(request):
	return render(request, 'packages.html')

def contact(request):
	return render(request, 'contact.html')

def portfolio(request):
	return render(request, 'portfolio.html')

templates/contact.html
	{% extends 'skeleton.html' %}
	{% load static from staticfiles %}
	{% block content %}

			<!-- start banner Area -->
			<section class="relative about-banner">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								Contact Us				
							</h1>	
							<p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="contact.html"> Contact Us</a></p>
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  

			<!-- Start contact-page Area -->
			<section class="contact-page-area section-gap">
				<div class="container">
					<div class="row">
						<div class="map-wrap" style="width:100%; height: 445px;" id="map"></div>
						<div class="col-lg-4 d-flex flex-column address-wrap">
							<div class="single-contact-address d-flex flex-row">
								<div class="icon">
									<span class="lnr lnr-home"></span>
								</div>
								<div class="contact-details">
									<h5>Binghamton, New York</h5>
									<p>
										4343 Hinkle Deegan Lake Road
									</p>
								</div>
							</div>
							<div class="single-contact-address d-flex flex-row">
								<div class="icon">
									<span class="lnr lnr-phone-handset"></span>
								</div>
								<div class="contact-details">
									<h5>00 (958) 9865 562</h5>
									<p>Mon to Fri 9am to 6 pm</p>
								</div>
							</div>
							<div class="single-contact-address d-flex flex-row">
								<div class="icon">
									<span class="lnr lnr-envelope"></span>
								</div>
								<div class="contact-details">
									<h5>support@colorlib.com</h5>
									<p>Send us your query anytime!</p>
								</div>
							</div>														
						</div>
						<div class="col-lg-8">
							<form class="form-area contact-form text-right" id="myForm" action="mail.php" method="post">
								<div class="row">	
									<div class="col-lg-6 form-group">
										<input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" class="common-input mb-20 form-control" required="" type="text">
									
										<input name="email" placeholder="Enter email address" pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" class="common-input mb-20 form-control" required="" type="email">

										<input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter subject'" class="common-input mb-20 form-control" required="" type="text">
									</div>
									<div class="col-lg-6 form-group">
										<textarea class="common-textarea form-control" name="message" placeholder="Enter Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'" required=""></textarea>				
									</div>
									<div class="col-lg-12">
										<div class="alert-msg" style="text-align: left;"></div>
										<button class="genric-btn primary" style="float: right;">Send Message</button>											
									</div>
								</div>
							</form>	
						</div>
					</div>
				</div>	
			</section>
			<!-- End contact-page Area -->

			{% endblock %}	

templates/packages.html
	{% extends 'skeleton.html' %}
	{% load static from staticfiles %}
	{% block content %}
			  
			<!-- start banner Area -->
			<section class="about-banner relative">
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								Tour Packages				
							</h1>	
							<p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="packages.html"> Tour Packages</a></p>
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->	

			<!-- Start hot-deal Area -->
			<section class="hot-deal-area section-gap">
				<div class="container">
		            <div class="row d-flex justify-content-center">
		                <div class="menu-content pb-70 col-lg-8">
		                    <div class="title text-center">
		                        <h1 class="mb-10">Today’s Hot Deals</h1>
		                        <p>We all live in an age that belongs to the young at heart. Life that is becoming extremely fast, day to.</p>
		                    </div>
		                </div>
		            </div>						
					<div class="row justify-content-center">
						<div class="col-lg-10 active-hot-deal-carusel">
							<div class="single-carusel">
								<div class="thumb relative">
									<div class="overlay overlay-bg"></div>
									<img class="img-fluid" src="img/packages/hot-deal.jpg" alt="">
								</div>
								<div class="price-detials">
									<a href="#" class="price-btn">Starting From <span>$250</span></a>
								</div>
								<div class="details">
									<h4 class="text-white">Ancient Architecture</h4>
									<p class="text-white">
										Cairo, Egypt
									</p>
								</div>								
							</div>
							<div class="single-carusel">
								<div class="thumb relative">
									<div class="overlay overlay-bg"></div>
									<img class="img-fluid" src="img/packages/hot-deal.jpg" alt="">
								</div>
								<div class="price-detials">
									<a href="#" class="price-btn">Starting From <span>$250</span></a>
								</div>
								<div class="details">
									<h4 class="text-white">Ancient Architecture</h4>
									<p class="text-white">
										Cairo, Egypt
									</p>
								</div>								
							</div>
							<div class="single-carusel">
								<div class="thumb relative">
									<div class="overlay overlay-bg"></div>
									<img class="img-fluid" src="img/packages/hot-deal.jpg" alt="">
								</div>
								<div class="price-detials">
									<a href="#" class="price-btn">Starting From <span>$250</span></a>
								</div>
								<div class="details">
									<h4 class="text-white">Ancient Architecture</h4>
									<p class="text-white">
										Cairo, Egypt
									</p>
								</div>								
							</div>														
						</div>
					</div>
				</div>	
			</section>
			<!-- End hot-deal Area -->
			

			<!-- Start destinations Area -->
			<section class="destinations-area section-gap">
				<div class="container">
		            <div class="row d-flex justify-content-center">
		                <div class="menu-content pb-40 col-lg-8">
		                    <div class="title text-center">
		                        <h1 class="mb-10">Popular Destinations</h1>
		                        <p>We all live in an age that belongs to the young at heart. Life that is becoming extremely fast, day to.</p>
		                    </div>
		                </div>
		            </div>						
					<div class="row">
						<div class="col-lg-4">
							<div class="single-destinations">
								<div class="thumb">
									<img src="img/packages/d1.jpg" alt="">
								</div>
								<div class="details">
									<h4>Holiday Sea beach Blue Ocean</h4>
									<p>
										United staes of America
									</p>
									<ul class="package-list">
										<li class="d-flex justify-content-between align-items-center">
											<span>Duration</span>
											<span>06 days and 7 nights</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Date</span>
											<span>18.04.2018</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Airport</span>
											<span>Changi</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Extras</span>
											<span>All Inclusive</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Price per person</span>
											<a href="#" class="price-btn">$250</a>
										</li>													
									</ul>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-destinations">
								<div class="thumb">
									<img src="img/packages/d2.jpg" alt="">
								</div>
								<div class="details">
									<h4>Holiday Sea beach Blue Ocean</h4>
									<p>
										United staes of America
									</p>
									<ul class="package-list">
										<li class="d-flex justify-content-between align-items-center">
											<span>Duration</span>
											<span>06 days and 7 nights</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Date</span>
											<span>18.04.2018</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Airport</span>
											<span>Changi</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Extras</span>
											<span>All Inclusive</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Price per person</span>
											<a href="#" class="price-btn">$250</a>
										</li>													
									</ul>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-destinations">
								<div class="thumb">
									<img src="img/packages/d3.jpg" alt="">
								</div>
								<div class="details">
									<h4>Holiday Sea beach Blue Ocean</h4>
									<p>
										United staes of America
									</p>
									<ul class="package-list">
										<li class="d-flex justify-content-between align-items-center">
											<span>Duration</span>
											<span>06 days and 7 nights</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Date</span>
											<span>18.04.2018</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Airport</span>
											<span>Changi</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Extras</span>
											<span>All Inclusive</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Price per person</span>
											<a href="#" class="price-btn">$250</a>
										</li>													
									</ul>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-destinations">
								<div class="thumb">
									<img src="img/packages/d4.jpg" alt="">
								</div>
								<div class="details">
									<h4>Holiday Sea beach Blue Ocean</h4>
									<p>
										United staes of America
									</p>
									<ul class="package-list">
										<li class="d-flex justify-content-between align-items-center">
											<span>Duration</span>
											<span>06 days and 7 nights</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Date</span>
											<span>18.04.2018</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Airport</span>
											<span>Changi</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Extras</span>
											<span>All Inclusive</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Price per person</span>
											<a href="#" class="price-btn">$250</a>
										</li>													
									</ul>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-destinations">
								<div class="thumb">
									<img src="img/packages/d5.jpg" alt="">
								</div>
								<div class="details">
									<h4>Holiday Sea beach Blue Ocean</h4>
									<p>
										United staes of America
									</p>
									<ul class="package-list">
										<li class="d-flex justify-content-between align-items-center">
											<span>Duration</span>
											<span>06 days and 7 nights</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Date</span>
											<span>18.04.2018</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Airport</span>
											<span>Changi</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Extras</span>
											<span>All Inclusive</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Price per person</span>
											<a href="#" class="price-btn">$250</a>
										</li>													
									</ul>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-destinations">
								<div class="thumb">
									<img src="img/packages/d6.jpg" alt="">
								</div>
								<div class="details">
									<h4>Holiday Sea beach Blue Ocean</h4>
									<p>
										United staes of America
									</p>
									<ul class="package-list">
										<li class="d-flex justify-content-between align-items-center">
											<span>Duration</span>
											<span>06 days and 7 nights</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Date</span>
											<span>18.04.2018</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Airport</span>
											<span>Changi</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Extras</span>
											<span>All Inclusive</span>
										</li>
										<li class="d-flex justify-content-between align-items-center">
											<span>Price per person</span>
											<a href="#" class="price-btn">$250</a>
										</li>													
									</ul>
								</div>
							</div>
						</div>																														
					</div>
				</div>	
			</section>
			<!-- End destinations Area -->
			

			<!-- Start home-about Area -->
			<section class="home-about-area">
				<div class="container-fluid">
					<div class="row align-items-center justify-content-end">
						<div class="col-lg-6 col-md-12 home-about-left">
							<h1>
								Did not find your Package? <br>
								Feel free to ask us. <br>
								We‘ll make it for you
							</h1>
							<p>
								inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that, as women, our behavior on the job is beyond reproach. inappropriate behavior is often laughed.
							</p>
							<a href="#" class="primary-btn text-uppercase">request custom price</a>
						</div>
						<div class="col-lg-6 col-md-12 home-about-right no-padding">
							<img class="img-fluid" src="img/packages/about-img.jpg" alt="">
						</div>
					</div>
				</div>	
			</section>
			<!-- End home-about Area -->

			{% endblock %}

templates/portfolio.html
{% extends 'skeleton.html' %}
{% load static from staticfiles %}
{% block content %}

{% endblock %}

templates/skeleton.html
{% load static from staticfiles %}
<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="img/fav.png">
		<!-- Author Meta -->
		<meta name="author" content="colorlib">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>Dolphins Tour and Travel</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
			<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
			<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
			<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
			<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">				
			<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">							
			<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">				
			<link rel="stylesheet" href="{% static 'css/main.css' %}">
		</head>
		<body>	
			<header id="header">
				<div class="header-top">
					<div class="container">
			  		<div class="row align-items-center">
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-left">
			  				<ul>
			  					<li><a href="#">Visit Us</a></li>
			  					<li><a href="#">Buy Tickets</a></li>
			  				</ul>			
			  			</div>
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-right">
							<div class="header-social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
							</div>
			  			</div>
			  		</div>			  					
					</div>
				</div>
				<div class="container main-menu">
					<div class="row align-items-center justify-content-between d-flex">
				      <div id="logo">
				        <a href="{% url 'main:home' %}"><img src="img/logo.png" alt="" title="" /></a>
				      </div>
				      <nav id="nav-menu-container">
				        <ul class="nav-menu">
				          <li><a href="{% url 'main:home' %}">Home</a></li>
				          <li><a href="{% url 'main:about' %}">About</a></li>
				          <li><a href="{% url 'main:services' %}">Services</a></li> 
				          <li><a href="{% url 'main:portfolio' %}">Portfolio</a></li>   		          
				          <li><a href="{% url 'main:contact' %}">Contact</a></li>
				        </ul>
				      </nav><!-- #nav-menu-container -->					      		  
					</div>
				</div>
			</header><!-- #header -->
			{% block content %}
			{% endblock %}

		<!-- start footer Area -->		
			<footer class="footer-area section-gap">
				<div class="container">

					<div class="row">
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>About Agency</h6>
								<p>
									The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point 
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Navigation Links</h6>
								<div class="row">
									<div class="col">
										<ul>
											<li><a href="#">Home</a></li>
											<li><a href="#">Feature</a></li>
											<li><a href="#">Services</a></li>
											<li><a href="#">Portfolio</a></li>
										</ul>
									</div>
									<div class="col">
										<ul>
											<li><a href="#">Team</a></li>
											<li><a href="#">Pricing</a></li>
											<li><a href="#">Blog</a></li>
											<li><a href="#">Contact</a></li>
										</ul>
									</div>										
								</div>							
							</div>
						</div>							
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Newsletter</h6>
								<p>
									For business professionals caught between high OEM price and mediocre print and graphic output.									
								</p>								
								<div id="mc_embed_signup">
									<form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscription relative">
										<div class="input-group d-flex flex-row">
											<input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
											<button class="btn bb-btn"><span class="lnr lnr-location"></span></button>		
										</div>									
										<div class="mt-10 info"></div>
									</form>
								</div>
							</div>
						</div>
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget mail-chimp">
								<h6 class="mb-20">InstaFeed</h6>
								<ul class="instafeed d-flex flex-wrap">
									<li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
								</ul>
							</div>
						</div>						
					</div>

					<div class="row footer-bottom d-flex justify-content-between align-items-center">
						<p class="col-lg-8 col-sm-12 footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Dolphins Tour and Travels</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
						<div class="col-lg-4 col-sm-12 footer-social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</footer>
			<!-- End footer Area -->	

			<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
			<script src="{% static 'js/popper.min.js' %}"></script>
			<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>			
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>		
 			<script src="{% static 'js/jquery-ui.js' %}"></script>					
  			<script src="{% static 'js/easing.min.js' %}"></script>			
			<script src="{% static 'js/hoverIntent.js' %}"></script>
			<script src="{% static 'js/superfish.min.js' %}"></script>	
			<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
			<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>						
			<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>					
			<script src="{% static 'js/owl.carousel.min.js' %}"></script>							
			<script src="{% static 'js/mail-script.js' %}"></script>	
			<script src="{% static 'js/main.js' %}"></script>	
		</body>
	</html>